[versions]
kotlin = "1.8.21"
arrow = "1.2.0-RC"
arrow-config = "0.11.0"
dokka = "1.8.10"
kotest = "5.6.2"
kotest-arrow = "1.3.3"
kover = "0.7.1"
kotlinBinaryCompatibilityValidator = "0.13.2"
knit = "0.4.0"
spotless = "6.19.0"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-arrow = { module = "io.kotest.extensions:kotest-assertions-arrow", version.ref = "kotest-arrow" }
kotest-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlinx-knit-test = { module = "org.jetbrains.kotlinx:kotlinx-knit-test", version.ref = "knit" }

[plugins]
arrow-config-formatter = { id = "io.arrow-kt.arrow-gradle-config-formatter", version.ref = "arrow-config" }
arrow-config-kotlin = { id = "io.arrow-kt.arrow-gradle-config-kotlin", version.ref = "arrow-config" }
arrow-config-nexus = { id = "io.arrow-kt.arrow-gradle-config-nexus", version.ref = "arrow-config" }
arrow-config-publish = { id = "io.arrow-kt.arrow-gradle-config-publish", version.ref = "arrow-config" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotest-multiplatform = { id = "io.kotest.multiplatform", version.ref = "kotest" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinBinaryCompatibilityValidator" }
kotlinx-knit = { id = "org.jetbrains.kotlinx.knit", version.ref = "knit" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
